apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-prod
resources:
  - ../../base
images:
  - name: app
    newName: ghcr.io/v-dev-cl/sample-app
    newTag: master   # LAB 1 FIXES THIS: mutable branch tag
configMapGenerator:
  - name: sample-app-config
    literals:
      - GREETING=hola prod
secretGenerator:
  - name: sample-app-secrets
    literals:
      - API_KEY=super-secret-prod-key   # LAB 3 FIXES THIS: secret committed to git
